### ISSUE TITLE
ClassNotFoundException using released toolkit

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.messagehub#9]
```
java.lang.ClassNotFoundException: com.ibm.streamsx.messagehub.operators.MessageHubConsumerOperator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:846)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:825)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.loadOperatorClass(OperatorAdapter.java:409)
	at com.ibm.streams.operator.internal.compile.OperatorCompileTime.verifyClassNameAndLibraries(OperatorCompileTime.java:202)
	at com.ibm.streams.operator.internal.compile.OperatorCompileTime.executeCompileTimeChecks(OperatorCompileTime.java:160)
	at com.ibm.streams.operator.internal.compile.OperatorCompileTime.main(OperatorCompileTime.java:131)

java.lang.ClassNotFoundException: com.ibm.streamsx.messagehub.operators.MessageHubProducerOperator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:846)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:825)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.loadOperatorClass(OperatorAdapter.java:409)
	at com.ibm.streams.operator.internal.compile.OperatorCompileTime.verifyClassNameAndLibraries(OperatorCompileTime.java:202)
	at com.ibm.streams.operator.internal.compile.OperatorCompileTime.executeCompileTimeChecks(OperatorCompileTime.java:160)
	at com.ibm.streams.operator.internal.compile.OperatorCompileTime.main(OperatorCompileTime.java:131)

**Comment by cancilla** [comment]
The operators are missing the `impl/lib/*` entry in the @Libraries annotation for each of the operators.
